import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header_Nav from "@/Components/header_nav";
import Loading from "@/Components/Loading";
import Loading_Redirect from "@/Components/Loading_Redirect";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chat AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        {/* Header */}
        <Header_Nav />
        {/* Content */}
        <main className="container mx-auto">{children}</main>
        {/* custom */}

        <Loading />
        <Loading_Redirect />
      </body>
    </html>
  );
}
